// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCD_3euSGK8bYAS_hba42o6m_jc2LWeSY',
    appId: '1:374257056564:web:ebdb9f67e0d0b9ce164361',
    messagingSenderId: '374257056564',
    projectId: 'report-e41e1',
    authDomain: 'report-e41e1.firebaseapp.com',
    storageBucket: 'report-e41e1.firebasestorage.app',
    measurementId: 'G-92S77K5NGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_bUhJvTvt7f0cGHnnBaIiYjTKcYbBlH8',
    appId: '1:374257056564:android:9217d491dc83dbf1164361',
    messagingSenderId: '374257056564',
    projectId: 'report-e41e1',
    storageBucket: 'report-e41e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQssL0FK-xASokKjuzzVmpVVDvnPue3k',
    appId: '1:374257056564:ios:f709cb0ab622c4cd164361',
    messagingSenderId: '374257056564',
    projectId: 'report-e41e1',
    storageBucket: 'report-e41e1.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQssL0FK-xASokKjuzzVmpVVDvnPue3k',
    appId: '1:374257056564:ios:f709cb0ab622c4cd164361',
    messagingSenderId: '374257056564',
    projectId: 'report-e41e1',
    storageBucket: 'report-e41e1.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCD_3euSGK8bYAS_hba42o6m_jc2LWeSY',
    appId: '1:374257056564:web:d9395a113a4f18cc164361',
    messagingSenderId: '374257056564',
    projectId: 'report-e41e1',
    authDomain: 'report-e41e1.firebaseapp.com',
    storageBucket: 'report-e41e1.firebasestorage.app',
    measurementId: 'G-HFD0LBN6P3',
  );
}
